config/routes.rb
Rails.application.routes.draw do
    root to: 'public/homes#top'
    
  namespace :public do
   get 'warning' => 'homes#warning', as: 'warning'
      resources :posts, except: [:edit] do
          resources :post_comments, only: [:create, :destroy]
           resource :favorites, only: [:create, :destroy]
           
           #検索
           collection do
             get 'search'
           end
      end
      
      resources :users, except: [:new, :destroy] do
         #フォロー機能
          post 'follow' => 'relationships#follow',as: 'follow'
          delete 'unfollow' => 'relationships#unfollow', as: 'unfollow'
          get 'followings' => 'relationships#followings', as: 'followings'
          get 'folloers' => 'relationships#followers', as: 'followers'
          
          member do
              get :favorites
          end
          # 退会機能
          get 'unsubscribe' =>'users#unsubscribe', as: 'unsubscribe'
          patch 'withdrawal' => 'users#withdrawal', as: 'withdrawal'
          
          # 検索
          collection do
            get 'search'
          end
      end
      resources :chats, only: [:show, :create]
      resources :groups, except: [:new] do
       get "join" => "groups#join"
       delete "all_destroy" => "groups#all_destroy"
       resources :group_messages, only: [:index, :create]
       
       collection do
         get 'search'
       end
      end
  end
  
  namespace :admin do
   root to: 'homes#top'
   
    resources :tags, only: [:index, :create, :edit, :update] do
     collection do
      get 'search'
     end
    end
    resources :users, only: [:index,:show] do
     # 退会機能
      get 'unsubscribe' =>'users#unsubscribe', as: 'unsubscribe'
      patch 'withdrawal' => 'users#withdrawal', as: 'withdrawal'
      
      collection do
        get 'search'
      end
    end
    resources :posts, only: [:index,:show, :destroy] do 
     resources :post_comments, only: [:destroy]
     collection do
      get 'search'
     end
    end
    resources :groups, only: [:index,:show, :destroy] do
        resources :group_messages, only: [:index]
        
        collection do
          get 'search'
        end
    end
  end
  
  
  
 #devise 
 # ユーザー用
 devise_for :users,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
   
 }
 devise_scope :user do
     post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
 end 

 # 管理者用
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
 }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    before_action :authenticate_admin!, except: [:top]
    def top
      
    end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/views/admin/homes/top.html.erb
    <div class="container" id= "admin-top">
        <% if admin_signed_in? %>
        <div class="row  justify-content-center mt-5"><h2 class="text-center">お疲れです！管理人さん！</h2></div>
        <div class="row justify-content-center mt-5">
            <div class="col-auto d-flex align-items-center admin-item">
                <%= link_to 'タグ一覧', admin_tags_path, class: "btn btn-info btn-lg " %>
            </div>
            <div class="col-auto d-flex align-items-center">
                <%= link_to 'ユーザー一覧', admin_users_path, class: "btn btn-outline-primary btn-lg" %>
            </div>
            <div class="col-auto d-flex align-items-center">
                <%= link_to '投稿一覧', admin_posts_path, class: "btn btn-outline-info btn-lg" %>
            </div>
            <div class="col-auto d-flex align-items-center">
                <%= link_to 'グループ一覧', admin_groups_path, class: "btn btn-outline-success btn-lg" %>
            </div> 
        </div>
        <% else %>
        <div class="row justify-content-center" >
            <h2 class="text-center mt-5">ようこそ！管理人さん！</h2>
        </div>
        <div class="row justify-content-center">
            <div class="col-sm col-md col-lg-4 d-flex align-items-center admin-item">
                <%= link_to 'ログイン', new_admin_session_path, class: "btn btn-info btn-block" %>
            </div>
        </div>
        <% end %>        
    </div>