config/routes.rb
Rails.application.routes.draw do
    root to: 'public/homes#top'
    
  namespace :public do
   get 'warning' => 'homes#warning', as: 'warning'
      resources :posts, except: [:edit] do
          resources :post_comments, only: [:create, :destroy]
           resource :favorites, only: [:create, :destroy]
           
           #検索
           collection do
             get 'search'
           end
      end
      
      resources :users, except: [:new, :destroy] do
         #フォロー機能
          post 'follow' => 'relationships#follow',as: 'follow'
          delete 'unfollow' => 'relationships#unfollow', as: 'unfollow'
          get 'followings' => 'relationships#followings', as: 'followings'
          get 'folloers' => 'relationships#followers', as: 'followers'
          
          member do
              get :favorites
          end
          # 退会機能
          get 'unsubscribe' =>'users#unsubscribe', as: 'unsubscribe'
          patch 'withdrawal' => 'users#withdrawal', as: 'withdrawal'
          
          # 検索
          collection do
            get 'search'
          end
      end
      resources :chats, only: [:show, :create]
      resources :groups, except: [:new] do
       get "join" => "groups#join"
       delete "all_destroy" => "groups#all_destroy"
       resources :group_messages, only: [:index, :create]
       
       collection do
         get 'search'
       end
      end
  end
  
  namespace :admin do
   root to: 'homes#top'
   
    resources :tags, only: [:index, :create, :edit, :update] do
     collection do
      get 'search'
     end
    end
    resources :users, only: [:index,:show] do
     # 退会機能
      get 'unsubscribe' =>'users#unsubscribe', as: 'unsubscribe'
      patch 'withdrawal' => 'users#withdrawal', as: 'withdrawal'
      
      collection do
        get 'search'
      end
    end
    resources :posts, only: [:index,:show, :destroy] do 
     resources :post_comments, only: [:destroy]
     collection do
      get 'search'
     end
    end
    resources :groups, only: [:index,:show, :destroy] do
        resources :group_messages, only: [:index]
        
        collection do
          get 'search'
        end
    end
  end
  
  
  
 #devise 
 # ユーザー用
 devise_for :users,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
   
 }
 devise_scope :user do
     post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
 end 

 # 管理者用
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
 }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_users, dependent: :destroy
    has_many :users, through: :group_users, dependent: :destroy
    has_many :group_messages, dependent: :destroy
    
    has_one_attached :profile_image
    
    belongs_to :user,optional: true
    
    validates :name, presence: true,length: { in: 1..30 }
    validates :introduction, presence: true,length: { in: 1..200 }
    
    def get_profile_image
      (profile_image.attached?) ? profile_image : 'mizu.jpg'
    end
    
      def self.ransackable_attributes(auth_object = nil)
         ["created_at", "id", "introduction", "name", "owner_id", "updated_at"]
      end
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @groups = Group.all
    
     @q     = Group.ransack(params[:q])
     @q_groups = @q.result(distinct: true)
   
  end

  def show
    @group  = Group.find(params[:id])
  end

  def destroy
    @group  = Group.find(params[:id])
     if @group.destroy
       redirect_to admin_groups_path
     end
  end
  
  def search
    @results = @q.result
  end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/views/admin/groups/_group_index.html.erb
<div class="container">
    <div class="row justify-content-center">
        <div class="col">
            <% groups.each do |group| %>
                <div class="card mt-3" style="width: 100%;">
                  <img class="bd-placeholder-img card-img-top"><div onselectstart="return false;" onmousedown="return false;"><%= image_tag group.get_profile_image, width: '150px', height: '150px' %></div></img>
                  <div class="card-body">
                    <h5 class="card-title"><%= group.name %></h5>
                    <p class="card-text"><%= group.introduction %></p>
                    <%= link_to '見てみる', admin_group_path(group), class: "btn btn-outline-info btn-sm" %>
                  </div>
                </div>
                <% end %>
        </div>
    </div>
</div>

app/views/admin/groups/index.html.erb
<div class="container page-height">
    <div class="row justify-cintent-center">
        <div class="col-sm col-md col-lg-2 px-5 px-sm-0 mx-auto">
            <div class="sidebar_fixed mt-5">
                <%= search_form_for @q, url: admin_groups_path do |f| %>
                <table>
                    <tr><%= f.search_field :name_cont %></tr>
                    <tr><%= f.submit 'グループ検索' %></tr>
                </table>
                <% end %>
            </div>
        </div>
        <div class="col-sm col-md col-lg-5 px-5 px-sm-0 mx-auto">
            <div class="admin-scroll">
                <%= render 'admin/groups/group_index', groups: @q_groups %>
            </div>
            
        </div>
    </div>
</div>

app/views/admin/groups/show.html.erb
<div class="container page-height">
    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg px-5 px-sm-0 mx-auto mt-5">
            <div onselectstart="return false;" onmousedown="return false;"><%= image_tag @group.get_profile_image, width: '150px', height: '150px' %></div>
             <table class= "table table-borderless">
                <tr>
                  <th>グループ名</th>
                  <th><%= @group.name %></th>
                </tr>
                <tr>
                  <th>紹介文</th>
                  <th><%= @group.introduction %></th>
                </tr>
                <tr>
                  <th>メンバー</th>
                  <th>
                    <% @group.users.each do |member| %>
                      <%= member.name %><br>
                    <% end %>
                  </th>
                </tr>
                  <td>
                      <%= link_to 'グループ削除',admin_group_path(@group),
                      method: :delete,data: { confirm: '本当に削除しますか？' } ,
                      class: "btn btn-sm btn-outline-danger" %>
                  </td>
                  <td><%= link_to 'チャットを始める', admin_group_group_messages_path(@group), class: "btn btn-outline-info" %></td>
                </tr>
             </table>
          <div>
              <%= link_to '一覧へ', admin_groups_path %>
          </div>
    </div>
</div>