config/routes.rb
Rails.application.routes.draw do
    root to: 'public/homes#top'
    
  namespace :public do
   get 'warning' => 'homes#warning', as: 'warning'
      resources :posts, except: [:edit] do
          resources :post_comments, only: [:create, :destroy]
           resource :favorites, only: [:create, :destroy]
           
           #検索
           collection do
             get 'search'
           end
      end
      
      resources :users, except: [:new, :destroy] do
         #フォロー機能
          post 'follow' => 'relationships#follow',as: 'follow'
          delete 'unfollow' => 'relationships#unfollow', as: 'unfollow'
          get 'followings' => 'relationships#followings', as: 'followings'
          get 'folloers' => 'relationships#followers', as: 'followers'
          
          member do
              get :favorites
          end
          # 退会機能
          get 'unsubscribe' =>'users#unsubscribe', as: 'unsubscribe'
          patch 'withdrawal' => 'users#withdrawal', as: 'withdrawal'
          
          # 検索
          collection do
            get 'search'
          end
      end
      resources :chats, only: [:show, :create]
      resources :groups, except: [:new] do
       get "join" => "groups#join"
       delete "all_destroy" => "groups#all_destroy"
       resources :group_messages, only: [:index, :create]
       
       collection do
         get 'search'
       end
      end
  end
  
  namespace :admin do
   root to: 'homes#top'
   
    resources :tags, only: [:index, :create, :edit, :update] do
     collection do
      get 'search'
     end
    end
    resources :users, only: [:index,:show] do
     # 退会機能
      get 'unsubscribe' =>'users#unsubscribe', as: 'unsubscribe'
      patch 'withdrawal' => 'users#withdrawal', as: 'withdrawal'
      
      collection do
        get 'search'
      end
    end
    resources :posts, only: [:index,:show, :destroy] do 
     resources :post_comments, only: [:destroy]
     collection do
      get 'search'
     end
    end
    resources :groups, only: [:index,:show, :destroy] do
        resources :group_messages, only: [:index]
        
        collection do
          get 'search'
        end
    end
  end
  
  
  
 #devise 
 # ユーザー用
 devise_for :users,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
   
 }
 devise_scope :user do
     post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
 end 

 # 管理者用
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
 }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
    has_many :posts, dependent: :destroy
    has_many :favorites, dependent: :destroy
    has_many :post_comments, dependent: :destroy
    
    has_one_attached :profile_image
    
    
    # DM機能
    has_many :user_rooms, dependent: :destroy
    has_many :chats, dependent: :destroy
    has_many :rooms, through: :user_rooms
    # グループ機能
    has_many :group_users, dependent: :destroy
    has_many :groups, through: :group_users, dependent: :destroy
    has_many :owned_groups, class_name: "Group"
    has_many :group_messages, dependent: :destroy
    

    # フォローをした、されたの関係
    has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
    
    # 一覧画面で使う
    has_many :followings, through: :relationships, source: :followed
    has_many :followers, through: :reverse_of_relationships, source: :follower
    
    
    validates :name,presence: true, uniqueness: true
    
    #した
    def follow(user)
      relationships.create(followed_id: user.id)
    end
    
    #はずした
    def unfollow(user)
      relationships.find_by(followed_id: user.id).destroy
    end
    
    #判定
    def following?(user)
      followings.include?(user)
    end
         
   def self.guest
    find_or_create_by(email: 'dazai_osamu@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "太宰 治(ゲストユーザー)"
      user.introduction = "こんにちは、私の代表作は「人間失格」です。教科書とは結構仲良しですよ。"
    end
   end
   
   def ensure_normal_user
     resource.email == 'dazai_osamu@example.com'
     resource.name == '太宰 治'
   end
   
   #ransuck
   def self.ransackable_attributes(auth_object = nil)
    ["email","name"]
   end
   
    def self.ransackable_associations(auth_object = nil)
    ["chats", "favorites", "followers", "followings", "post_comments", "posts", "relationships", "reverse_of_relationships", "rooms", "user_rooms"]
    end
    
    
    def active_for_authentication?
      super && (is_deleted == false)
    end
    
    def get_profile_image
      (profile_image.attached?) ? profile_image : 'no_image.jpg'
    end
    
    
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
   before_action :authenticate_admin!
  def index
    @users= User.all
    
    @q     = User.ransack(params[:q])
    @q_users = @q.result(distinct: true)
  end

  def destroy
     @user = User.find(params[:id])
  end

  def show
     @user = User.find(params[:id])
  end
  
  def withdrawal
    @user = User.find(params[:user_id])
    if @user.is_deleted == true
       @user.update(is_deleted: false)
       flash[:notice] = "復活処理を実行いたしました"
       redirect_to admin_user_path(@user)
    else
      @user.update(is_deleted: true)
      flash[:notice] = "退会処理を実行いたしました"
      redirect_to admin_user_path(@user)
    end
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/_user_card.html.erb
<% q_users.each do |user| %>
    <div class="card bg-transparent mt-3">
      <h5 class="card-header"><%= user.name %></h5>
      <div class="card-body">
        <p class="card-text"><%= user.email %></p>
        <p class="card-text"><%= user.introduction %></p>
        <p class="card-text"><%= user.created_at.to_s(:datetime_jp) %></p>
       <div class="row justify-content-end">
           <div class="col-2">
               <%= link_to '詳細', admin_user_path(user), class: "btn btn-primary" %>
           </div>
       </div>   
      </div>
    </div>
<%end%>

app/views/admin/users/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm col-md col-lg-2 px-5 px-sm-0 mx-auto mt-5">
            <div class="sidebar_fixed">
                <%= search_form_for @q, url: admin_users_path do |f| %>
                <table>
                    <tr><%= f.search_field :name_cont %></tr>
                    <tr><%= f.submit 'ユーザー検索' %></tr>
                </table>
                <% end %>
            </div>
        </div>
        <div class="ccol-sm col-md col-lg-8 px-sm-0 mx-auto">
            <div class="admin-scroll">
               <%= render 'admin/users/user_card', q_users: @q_users %>
            </div>
        </div>
    </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
    <h2 class= "text-center mt-5">ユーザープロフィール</h2>
        <div class="row mt-5">
            <div class="col-sm-12 col-md-8 col-lg-8 px-5 px-sm-0 mx-auto">
                <table class='table table-borderless'>
                  <!--<tr>%= image_tag user.get_profile_image, size:'100x100' %></tr>-->
                  <tr>
                    <th>ニックネーム</th>
                    <th><%= @user.name %></th>
                  </tr>
                  <tr>
                      <th>メールアドレス</th>
                      <th><%= @user.email %></th>
                  </tr>
                  <tr>
                    <th>自己紹介</th>
                    <th><%= @user.introduction %></th>
                  </tr>
                  <tr>
                    <th>フォロー</th>
                    <th><%= @user.followings.count%></th>
                  </tr>
                  <tr>
                    <th>フォロワー</th>
                    <th><%= @user.followers.count %></th>
                  </tr>
                  <tr>
                      <th>登録日時</th>
                      <th><%= @user.created_at.to_s(:datetime_jp) %></th>
                  </tr>
                  <tr>
                      <th>ユーザー削除</th>
                      <th>
                          <% if @user.is_deleted == false %>
                              <%= link_to "退会させる", admin_user_withdrawal_path(@user), method: :patch, data: { confilm: "本当に退会させますか？" } %>
                          <% else %>
                              <%= link_to "復活させる", admin_user_withdrawal_path(@user), method: :patch, data: { confilm: "本当に復活させますか？" } %>
                          <% end %>
                      </th>
                  </tr>
                  <tr>
                      <th>状態</th>
                      <th>
                       <% if @user.is_deleted == false %>
                           <b class="text-success">有効</b>
                       <% else %>
                           <b class="text-black-50">退会</b>
                       <% end %>
                      </th>
                     
                  </tr>
                </table>
                
            </div>
        </div>
    </div>
</div>