config/routes.rb
Rails.application.routes.draw do
    root to: 'public/homes#top'
    
  namespace :public do
   get 'warning' => 'homes#warning', as: 'warning'
      resources :posts, except: [:edit] do
          resources :post_comments, only: [:create, :destroy]
           resource :favorites, only: [:create, :destroy]
           
           #検索
           collection do
             get 'search'
           end
      end
      
      resources :users, except: [:new, :destroy] do
         #フォロー機能
          post 'follow' => 'relationships#follow',as: 'follow'
          delete 'unfollow' => 'relationships#unfollow', as: 'unfollow'
          get 'followings' => 'relationships#followings', as: 'followings'
          get 'folloers' => 'relationships#followers', as: 'followers'
          
          member do
              get :favorites
          end
          # 退会機能
          get 'unsubscribe' =>'users#unsubscribe', as: 'unsubscribe'
          patch 'withdrawal' => 'users#withdrawal', as: 'withdrawal'
          
          # 検索
          collection do
            get 'search'
          end
      end
      resources :chats, only: [:show, :create]
      resources :groups, except: [:new] do
       get "join" => "groups#join"
       delete "all_destroy" => "groups#all_destroy"
       resources :group_messages, only: [:index, :create]
       
       collection do
         get 'search'
       end
      end
  end
  
  namespace :admin do
   root to: 'homes#top'
   
    resources :tags, only: [:index, :create, :edit, :update] do
     collection do
      get 'search'
     end
    end
    resources :users, only: [:index,:show] do
     # 退会機能
      get 'unsubscribe' =>'users#unsubscribe', as: 'unsubscribe'
      patch 'withdrawal' => 'users#withdrawal', as: 'withdrawal'
      
      collection do
        get 'search'
      end
    end
    resources :posts, only: [:index,:show, :destroy] do 
     resources :post_comments, only: [:destroy]
     collection do
      get 'search'
     end
    end
    resources :groups, only: [:index,:show, :destroy] do
        resources :group_messages, only: [:index]
        
        collection do
          get 'search'
        end
    end
  end
  
  
  
 #devise 
 # ユーザー用
 devise_for :users,skip: [:passwords], controllers: {
   registrations: "public/registrations",
   sessions: 'public/sessions'
   
 }
 devise_scope :user do
     post 'public/guest_sign_in', to: 'public/sessions#guest_sign_in'
 end 

 # 管理者用
 devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
   sessions: "admin/sessions"
 }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_admin_header.html.erb
<header>
  <a class="logotype" href="/"><%= image_tag 'logo' %></a>
    <p id="notice"><%= notice %></p>
  <nav>
    <input id="menu__toggle" type="checkbox" />
    <label class="menu__btn" for="menu__toggle">
      <span></span>
    </label>
    <ul class="menu__box">
     <% if admin_signed_in? %>
       <li><a class="menu__item" href="#">
            <%= link_to :back,class: 'nav-link text-white' do %>
                戻る
            <% end %>
        </a></li>
        <li><a class="menu__item" href="#">
            <%= link_to admin_root_path,class: 'nav-link text-white' do %>
                管理者トップページ
            <% end %>
        </a></li>
        <li><a class="menu__item" href="#">
            <%=  link_to admin_tags_path,class: 'nav-link text-white' do %>
              タグ一覧
            <% end %>
        </a></li>
        <li><a class="menu__item" href="#">
            <%=  link_to admin_users_path,class: 'nav-link text-white' do %>
               ユーザー一覧
            <% end %>
        </a></li>
        <li><a class="menu__item" href="#">
            <%=  link_to admin_posts_path ,class: 'nav-link text-white' do %>
                投稿一覧
            <% end %>
        </a></li>
        <li><a class="menu__item" href="#">
            <%= link_to admin_groups_path, class: 'nav-link text-white' do %>
                チャットグループ一覧
            <% end %>
        </a></li>
        <li><a class="menu__item" href="#">
            <%= link_to destroy_admin_session_path, method: :delete,class: 'nav-link text-white' do %>
                 ログアウト
            <% end %>
        </a></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_footer.html.erb
<footer>
    <div class="container mt-5 ">
        <div class="row">
            <div class="mx-auto mb-5">
                <%= link_to 'ご利用時の注意事項', public_warning_path %>
            </div>
        </div>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <a class="logotype" href="/"><%= image_tag 'logo' %></a>
  <nav>
    <input id="menu__toggle" type="checkbox" />
    <label class="menu__btn" for="menu__toggle">
      <span></span>
    </label>
    <ul class="menu__box">
     <% if user_signed_in? %>
     <li>
         <p id="notice"><%= notice %></p>
     </li>
     <li>
         <p> <%= current_user.name %> さん！</p>
     </li>
      <li><a class="menu__item" href="#">
          <%= link_to public_user_path(current_user),class: 'nav-link text-white' do %>
               プロフィール
          <% end %>
      </a></li>
      <li><a class="menu__item" href="#">
          <%=  link_to public_users_path,class: 'nav-link text-white' do %>
              アニメ好きの人々
          <% end %>
      </a></li>
      <li><a class="menu__item" href="#">
          <%=  link_to public_posts_path ,class: 'nav-link text-white' do %>
              みんなの投稿
          <% end %>
      </a></li>
      <li><a class="menu__item" href="#">
          <%= link_to public_groups_path, class: 'nav-link text-white' do %>
              チャットグループ
          <% end %>
      </a></li>
      <li><a class="menu__item" href="#">
          <%= link_to destroy_user_session_path, method: :delete,class: 'nav-link text-white' do %>
               ログアウト
          <% end %>
      </a></li>
      <li><a class="menu__item" href="#">
            <%= link_to :back,class: 'nav-link text-white' do %>
                戻る
            <% end %>
        </a></li>
     <% else %>
      <li>
         <p id="notice"><%= notice %></p>
     </li>
      <li><a class="menu__item" href="#">
          <%= link_to new_user_registration_path,class: 'nav-link text-white' do %>
               新規ユーザー登録
          <% end %>
      </a></li>
      <li><a class="menu__item" href="#">
          <%= link_to new_user_session_path ,class: 'nav-link text-white' do %>
              ログイン
          <% end %>
      </a></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_post_card.html.erb
<% @posts.each do |post| %>
  <div class="card w-100 mt-3" style="width: 18rem;" href='/public/posts/:id'>
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= post.user.name %></h6>
      <p class="card-text"><%= post.body %></p>
      <a>
        <%= link_to  public_post_path(post) do %>
          <i class="fas fa-comments"></i> 見る
        <% end %>
      </a>
      <a><%= render "public/favorites/btn", post: post %></a>
      <p style="text-align: right"><%= post.created_at.strftime("%Y年%m月%d日") %></p>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>アニメで話そ</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="back-img">
      <div class="back-color">
        <% if admin_signed_in? %>
          <%= render 'layouts/admin_header' %>
        <% else %>
          <%= render 'layouts/header' %>
        <% end %>
        <main oncontextmenu="return false;" onselectstart="return false;">
          <%= yield %>
        </main>
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
  
</html>